Repository frc2204/ramdocs, pull requests merged in 2023-08, with the labels that each got.

#7 Enhance calipers and credits
  docs/fabrication/hand-tools/calipers.md
  docs/fabrication/overview.md
Labels: enhancement

#11 Branding changes and typo fixes
  docs/business/overview.md
  docs/business/resources/branding.md
Labels: documentation

#9 Outline for ALL Handtools
  docs/fabrication/hand-tools/chain-breakers.md
  docs/fabrication/hand-tools/files.md
  docs/fabrication/hand-tools/hammer.md
  docs/fabrication/hand-tools/hand-saws.md
  docs/fabrication/hand-tools/hex-keys.md
  docs/fabrication/hand-tools/knives.md
  docs/fabrication/hand-tools/levels.md
  docs/fabrication/hand-tools/marking-tools.md
  docs/fabrication/hand-tools/measuring-tools.md
  docs/fabrication/hand-tools/pliers.md
  docs/fabrication/hand-tools/punches.md
  docs/fabrication/hand-tools/screwdriver.md
  docs/fabrication/hand-tools/sockets.md
  docs/fabrication/hand-tools/squares.md
  docs/fabrication/hand-tools/vises.md
  docs/fabrication/hand-tools/wrench.md
Labels: documentation, enhancement

#10 Added Table of contents for Collections, Control Flow, Loops, and Fun…
  docs/programming/kotlin/fundamentals/collections.md
  docs/programming/kotlin/fundamentals/control-flow.md
  docs/programming/kotlin/fundamentals/functions.md
  docs/programming/kotlin/fundamentals/loops.md
Labels: documentation, enhancement
